language: python
matrix:
  include:
    - python: 2.7
      env:
        - INSTALLER=Miniconda-latest-Linux-x86_64.sh
        - CONDA_INSTALL="bsddb"
    - python: 3.5
      env:
        - INSTALLER=Miniconda3-latest-Linux-x86_64.sh
        - CONDA_INSTALL=""
    - os: osx
      # python language is not supported on osx
      # due to https://github.com/travis-ci/travis-ci/issues/4729
      # because miniconda is used,
      # pretend to be another language which does not error
      language: objective-c
      env:
        - INSTALLER=Miniconda2-latest-MacOSX-x86_64.sh
        - CONDA_INSTALL=""
before_install:
  - if [ ! -e $HOME/conda/bin/activate ]; then
    wget -nc https://repo.continuum.io/miniconda/$INSTALLER;
    bash $INSTALLER -f -b -p $HOME/conda;
    fi
  - source $HOME/conda/bin/activate root
  - conda install -y -q -c https://conda.anaconda.org/rdkit rdkit setuptools pytables pandas coverage $CONDA_INSTALL
install:
  - pip install -r requirements.txt
script: py.test --cov
after_script:
  - pip install codacy_coverage
  - coverage xml
  - python-codacy-coverage -r coverage.xml
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/conda
before_cache:
  - rm $HOME/.cache/pip/log/debug.log $HOME/conda/bin/kripodb $HOME/conda/lib/*/*/kripodb.egg-link
