language: python
before_install:
  - if [ ! -e conda/bin/activate ]; then
    wget -nc https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh;
    bash Miniconda-latest-Linux-x86_64.sh -b -p conda;
    fi
  - source conda/bin/activate root
  - conda install -y -q -c https://conda.anaconda.org/rdkit rdkit pytables bsddb pandas coverage sphinx
install:
  - pip install -r requirements.txt
script:
  - nosetests
  - cd docs && make html
after_script:
  - pip install codacy_coverage
  - coverage xml
  - python-codacy-coverage -r coverage.xml
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
    - conda
before_cache:
  - rm $HOME/.cache/pip/log/debug.log conda/bin/kripodb conda/lib/*/*/kripo.egg-link
