language: python
before_install:
  - if [ ! -e $HOME/conda/bin/activate ]; then
    wget -nc https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh;
    bash Miniconda-latest-Linux-x86_64.sh -f -b -p $HOME/conda;
    fi
  - source $HOME/conda/bin/activate root
  - conda install -y -q -c https://conda.anaconda.org/rdkit rdkit pytables bsddb pandas coverage sphinx
install:
  - pip install -r requirements.txt
script:
  - nosetests
  - cd docs && make html
after_script:
  - pip install codacy_coverage
  - coverage xml
  - python-codacy-coverage -r coverage.xml
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/conda
before_cache:
  - rm $HOME/.cache/pip/log/debug.log $HOME/conda/bin/kripodb $HOME/conda/lib/*/*/kripo.egg-link
